# Generated by Django 4.2.13 on 2024-06-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_remove_product_description_remove_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
    ]
